export const FETCH_USER_ID = 'FETCH_USER_ID';
export const FETCH_USER_ID_SUCCESS = 'FETCH_USER_ID_SUCCESS';
export const FETCH_USER_ID_FAILURE = 'FETCH_USER_ID_FAILURE';

export const FETCH_USER_MOVIE_LIST = 'FETCH_USER_MOVIE_LIST';
export const FETCH_USER_MOVIE_LIST_SUCCESS = 'FETCH_USER_MOVIE_LIST_SUCCESS';
export const FETCH_USER_MOVIE_LIST_FAILURE = 'FETCH_USER_MOVIE_LIST_FAILURE';

export const FETCH_USER_FRIEND_LIST = 'FETCH_USER_FRIEND_LIST';
export const FETCH_USER_FRIEND_LIST_SUCCESS = 'FETCH_USER_FRIEND_LIST_SUCCESS';
export const FETCH_USER_FRIEND_LIST_FAILURE = 'FETCH_USER_FRIEND_LIST_FAILURE';

export const FETCH_TMDB_MOVIES = 'FETCH_TMDB_MOVIES';
export const FETCH_TMDB_MOVIES_SUCCESS = 'FETCH_TMDB_MOVIES_SUCCESS';
export const FETCH_TMDB_MOVIES_FAILURE = 'FETCH_TMDB_MOVIES_FAILURE';

export const SELECT_FRIEND_PROFILE = 'SELECT_FRIEND_PROFILE';

export const UPDATE_FAVORITE_STATUS = 'UPDATE_FAVORITE_STATUS';
export const UPDATE_FAVORITE_STATUS_SUCCESS = 'UPDATE_FAVORITE_STATUS_SUCCESS';
export const UPDATE_FAVORITE_STATUS_FAILURE = 'UPDATE_FAVORITE_STATUS_FAILURE';

export const UPDATE_WATCHLIST_STATUS = 'UPDATE_WATCHLIST_STATUS';
export const UPDATE_WATCHLIST_STATUS_SUCCESS = 'UPDATE_WATCHLIST_STATUS_SUCCESS';
export const UPDATE_WATCHLIST_STATUS_FAILURE = 'UPDATE_WATCHLIST_STATUS_FAILURE';

export const UPDATE_SEEN_STATUS = 'UPDATE_SEEN_STATUS';
export const UPDATE_SEEN_STATUS_SUCCESS = 'UPDATE_SEEN_STATUS_SUCCESS';
export const UPDATE_SEEN_STATUS_FAILURE = 'UPDATE_SEEN_STATUS_FAILURE';

export const REMOVE_FROM_LISTS = 'REMOVE_FROM_LISTS';
export const REMOVE_FROM_LISTS_SUCCESS = 'REMOVE_FROM_LISTS_SUCCESS';
export const REMOVE_FROM_LISTS_FAILURE = 'REMOVE_FROM_LISTS_FAILURE';

